Repository adobe/aem-cif-project-archetype, pull requests merged in 2020-04, with the labels that each got.

#98 CIF-1317 - Add support for virtual products to MyProductTeaser component
  src/main/archetype/core/src/main/java/core/models/MyProductTeaserImpl.java
  src/main/archetype/pom.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/commerce/productteaser/productteaser.html
Labels: To Verify, enhancement

#100 CIF-1256 - Better customizable PLP/PDP URL generation
  src/main/archetype/samplecontent/src/main/content/META-INF/vault/filter.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/apps/__appsFolderName__/config/com.adobe.cq.commerce.core.components.internal.services.UrlProviderImpl.config
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/localhost.4503/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/localhost.4503/category-page-reverse/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/localhost.4503/category-page/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/localhost.4503/product-page-reverse/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/localhost.4503/product-page/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/localhost.80/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/localhost.80/category-page-reverse/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/localhost.80/category-page/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/localhost.80/product-page-reverse/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/etc/map.publish/http/localhost.80/product-page/.content.xml
Labels: Verified

#102 CIF-1324 - Only one side panel should be open at a time
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/navigation/navigation-aem.css
Labels: bug

#104 CIF-1355 - MVP Faceted Search - Styling
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productlist/productlist-component.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/searchresults/searchresults-component.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/css.txt
Labels: To Verify, bug
