Repository adobe/aem-cif-project-archetype, pull requests merged in 2020-05, with the labels that each got.

#105 CIF-1371 - The Venia demo store should come with a product binding created
  src/main/archetype/samplecontent/src/main/content/META-INF/vault/filter.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/var/commerce/products/__confFolderName__-default/.content.xml
Labels: Verified

#106 CIF-1213: Improve Venia test coverage to meet CM goals
  src/main/archetype/core/pom.xml
  src/main/archetype/core/src/main/java/core/models/MyProductTeaserImpl.java
  src/main/archetype/core/src/test/java/core/models/MyProductTeaserImplTest.java
Labels: bug

#107 CIF-1354 - Refactor searchresults and productlist components
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-cif/.content.xml
Labels: enhancement

#108 CIF-1376 - add ACL for cloudconfig
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/cloudconfigs/commerce/_rep_policy.xml
Labels: bug

#109 CIF-1395 - The custom category page shows the category in list view
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/category-page/initial/.content.xml
Labels: Verified, bug
