Repository adobe/aem-cif-project-archetype, pull requests merged in 2020-03, with the labels that each got.

#89 CIF-1237 - Use generic authoring placeholder of WCM Core Components for all CIF Components
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/featuredcategorylist/categorylist.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productcarousel/productcarousel.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productlist/productlist-component.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productteaser/teaser.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/commerce/productteaser/productteaser.html
Labels: enhancement

#90 CIF-1306 - move CIF Connector dependency to sample project
  README.md
  src/main/archetype/ui.apps/pom.xml
Labels: bug

#88 CIF-1134 Unified configuration of site settings
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/language-masters/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/us/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/us/en/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/us/en/products/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/_cq_dialog/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/_cq_dialog/content/items/tabs/items/commerce/items/column/items/magentoSection/items/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/_cq_dialog/content/items/tabs/items/commerce/items/column/items/magentoSection/items/categoryFilter/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/_cq_dialog/content/items/tabs/items/commerce/items/column/items/magentoSection/items/productFilter/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/rootpage/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/cloudconfigs/commerce/.content.xml
Labels: enhancement

#94 CIF-1309 - remove productcarousel CSS selector and fix CSS
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productcarousel/productcarousel.css
Labels: bug

#95 CIF-1303 - add optional title support for related products & product …
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productcarousel/productcarousel.css
Labels: enhancement

#96 CIF-1305 - Support Grouped Products
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/product/product.css
Labels: Verified, enhancement

#97 CIF-1315 - JS of CIF Core Components should be loaded via theme clientlib
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-cif/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-cif/css.txt
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-cif/js.txt
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/customfooterlibs.html
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/customheaderlibs.html
Labels: To Verify, enhancement
