Repository adobe/aem-cif-project-archetype, pull requests merged in 2020-01, with the labels that each got.

#64 CIF-1149 - make cq:graphqlClient property only editable on the site root page to work with MSM rollouts
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/language-masters/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/language-masters/en/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/us/.content.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/us/en/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/_cq_dialog/content/items/tabs/items/commerce/items/column/items/magentoSection/items/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/_cq_dialog/content/items/tabs/items/commerce/items/column/items/magentoSection/items/categoryFilter/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/_cq_dialog/content/items/tabs/items/commerce/items/column/items/magentoSection/items/productFilter/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/rootpage/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/landing-page/initial/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/root-page/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/root-page/initial/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/root-page/policies/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/root-page/structure/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/root-page/structure/_jcr_content/root/header/logo.svg
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/root-page/thumbnail.png
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/root-page/thumbnail.png.dir/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/root-page/thumbnail.png.dir/_jcr_content/_dam_thumbnails/_dam_thumbnail_300.png
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/root-page/thumbnail.png.dir/_jcr_content/_dam_thumbnails/_dam_thumbnail_319.png
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/root-page/thumbnail.png.dir/_jcr_content/_dam_thumbnails/_dam_thumbnail_48.png
  src/main/archetype/ui.content/src/main/content/jcr_root/content/__contentFolderName__/.content.xml
Labels: To Verify, bug

#62 CIF-1164 - Improve responsiveness of product carousel component
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productcarousel/productcarousel.css
Labels: To Verify, enhancement

#63 CIF-1153 - Generic related product component
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/commerce/relatedproducts/.content.xml
Labels: Verified, enhancement

#68 CIF-1187 - fix cloud service configurations by adding missing config root folder
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/cloudconfigs/.content.xml
Labels: To Verify, bug

#69 CIF-905 - AEM CIF Core Component - XF
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/experiencefragment/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/xfpage/.content.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/xfpage/body.html
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/policies/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/experience-fragment-page/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/experience-fragment-page/initial/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/experience-fragment-page/policies/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/experience-fragment-page/structure/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/experience-fragment-page/thumbnail.png
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/experience-fragment-page/thumbnail.png.dir/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/experience-fragment-page/thumbnail.png.dir/_jcr_content/_dam_thumbnails/_dam_thumbnail_128.png
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/experience-fragment-page/thumbnail.png.dir/_jcr_content/_dam_thumbnails/_dam_thumbnail_300.png
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/experience-fragment-page/thumbnail.png.dir/_jcr_content/_dam_thumbnails/_dam_thumbnail_48.png
Labels: To Verify, enhancement

#71 CIF-1160 - Demo Env build on CM fails because of wrong parent version
  .circleci/ci/deploy-ams.js
Labels: Verified, releng

#73 releng - Update dependencies for upcoming release / CIF-1175
  .circleci/config.yml
  src/main/archetype/core/src/main/java/core/models/MyProductTeaserImpl.java
  src/main/archetype/pom.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/commerce/productteaser/productteaser.html
Labels: releng

#74 @trivial - removed unused cssid variable
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-base/.content.xml
Labels: bug

#75 releng - Update versions in README
  README.md
  VERSIONS.md
Labels: releng
