Repository adobe/aem-cif-project-archetype, pull requests merged in 2020-02, with the labels that each got.

#76 Avoid having "venia" in resource type
  src/main/archetype/core/src/main/java/core/models/MyProductTeaserImpl.java
Labels: bug

#79 @trivial - update dependencies
  README.md
  src/main/archetype/pom.xml
Labels: releng

#77 CIF-1196 - Update pricing information on product component
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/product/product.css
Labels: To Verify, enhancement

#81 CIF-1197 - Update pricing information on product list component
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/product/product.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productcarousel/productcarousel.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productlist/productlist-component.css
Labels: To Verify, enhancement

#83 CIF-1224 - Pagination in productlist component cannot handle large product sets
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productlist/productlist-aem.css
Labels: enhancement

#85 CIF-1246 - Fix CSS bug in searchbar
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/header/header-component.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/minicart/minicart.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/navigation/navigation-component.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/product/product.css
Labels: To Verify, bug

#86 CIF-1238 - Zooming out browser does not resize images of product list…
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/common/common.css
Labels: To Verify, bug

#87 CIF-1296 - Fix the styling of pagination bar
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productlist/productlist-aem.css
Labels: bug

#84 CIF-1251 - Add advanced pricing information to product teaser
  src/main/archetype/core/src/main/java/core/models/MyProductTeaserImpl.java
  src/main/archetype/pom.xml
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productteaser/teaser.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/commerce/productteaser/productteaser.html
Labels: Verified, enhancement
