Repository adobe/aem-cif-project-archetype, pull requests merged in 2020-06, with the labels that each got.

#113 CIF-1364: Added class for results count
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/productlist/productlist-component.css
Labels: To Verify, enhancement

#111 CIF-1365 - Support product sorting
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/searchresults/searchresults-component.css
Labels: enhancement

#115 CIF-1439 - GraphQL Client has to be manually added to Experience Frag…
  src/main/archetype/samplecontent/src/main/content/META-INF/vault/filter.xml
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/experience-fragments/__contentFolderName__/.content.xml
Labels: Verified, bug

#116 CIF-1406: Search results template fix
  src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/us/en/search/.content.xml
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/search-results/structure/.content.xml
Labels: Verified, bug

#114 Load Venia loading indicator (logo.svg) via CSS
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/components/loadingindicator/loader.css
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/css.txt
  src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/theme/resources/logo.svg
Labels: Verified, bug

#118 CIF-1156 - Live copy catalog does not show if node name is not language code
  src/main/archetype/pom.xml
Labels: Verified, bug

#117 @releng - Replacing 'all' WCM Core components dependencies with its c…
  src/main/archetype/all/pom.xml
  src/main/archetype/pom.xml
  src/main/archetype/ui.apps/pom.xml
Labels: Verified, bug

#119 CIF-1404 - Editing support for cq:catalogPath
  src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/cloudconfigs/commerce/.content.xml
Labels: Verified, enhancement

#120 @releng Update com.adobe.commerce.cif.graphql-client dependency to version `1.6.0`
  src/main/archetype/pom.xml
Labels: releng
